version: '2.1'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana
    container_name: grafana
    entrypoint: ["bash", "-c", "wget -P /etc/grafana/provisioning/dashboards https://raw.githubusercontent.com/epfl-si/external-noc/master/roles/grafana/files/provisioning/dashboards/PhDAssess-ZeebeDB.json; /run.sh"]
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/provisioning/dashboards/nodejs_application_dashboard.json:/etc/grafana/provisioning/dashboards/nodejs_application_dashboard.json
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 4000:3000
    expose:
      - 4000
    networks:
      - monitoring
  zeebe-db-monitor:
    build:
      context: .
    volumes:
      - ${DOCKER_COMPOSE_ZEEBE_DATA_RO_PATH}:/zeebe-data-ro:ro
      - ${DOCKER_COMPOSE_ZEEBE_DATA_RW_BASE_PATH}:/zeebe-data-rw
    environment:
      - ZEEBE_DATA_RO_PATH=/zeebe-data-ro
      - ZEEBE_DATA_RW_BASE_PATH=/zeebe-data-rw
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - monitoring
