version: '2.1'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring
#  grafana:
#    image: grafana/grafana
#    container_name: grafana
#    volumes:
#      - grafana_data:/var/lib/grafana
#      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#    environment:
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#    ports:
#      - 3000:3000
#    expose:
#      - 3000
#    networks:
#      - monitoring
  zeebe-snapshots-monitor:
    build:
      context: .
    volumes:
      - .:/app
      - ${SNAPSHOT_PATH}:/snapshots-ro
      - ${SNAPSHOT_PATH}
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - monitoring
