apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PA7DAED22D5425F49
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
